### ISSUE TITLE
Join Key Improvements

### ISSUE THREAD

**Issue by BluSyn** [bcoin-org/bmultisig#45]
During implementation I've been considering 2 major changes to how cosigner `joinKey` works would make the system much more robust.

1. The `joinKey` should be deterministically generated by the user creating the wallet, and should not be know-able by the server. This can be done by making it a signature using the creator's private key. The server can validate the joinKey with the creators' public key. In a "public wallet server" scenario, this prevents the server operator from hi-jacking the join process, or any "man-in-the-middle" scenario.

2. The `joinKey` should be serialized with both the key + wallet name. Currently in order for cosigners to join a wallet, they need many pieces of information: API Key, Wallet Name, Join Key. I think the `joinKey` should return as a serialized combination of all auth information, so the client can display or read a simple QR code to join a multisig wallet. This would also help in a "public wallet server" scenario, where the wallet name may be auto-generated.

@nodar-chkuaselidze

**Comment by tynes** [comment]
This PR begins to address the `joinKey` upgrades in regards to the message signing - https://github.com/bcoin-org/bledger/pull/34

**Comment by nodar-chkuaselidze** [comment]
This is more or less related to authentication mechanisms. But we can talk about
authentication issues on different thread.

First implementation of the protocol, does not consider operator attacks
(Even though first proposal I was thinking about was kinda decentralized bmultisig ^^),
so server gives you joinKey and even if you loose that key, admin can recover it for you.

Non-Operator MITM attacks can be handled by HTTPS and lightweight joinKey verification
(below).

### Trustless bmultisig with current structure.
Even if you need signed join key to join the server, it still relies on operator
because operator can always MITM you(e.g. replace xpub).
So unless we drastically change architecture and remove most of the capabilities
from the server to the client side (We can start working and sketching it.).

If you want joinKey to contain signature and be relatively secure,
it changes several things and is tougher to verify:

First you need to create as many signatures using deterministic derivation,
as many cosigners you have. Otherwise, you will only have one joinKey
and after first cosigner joins, operator can use it to join other cosigners as well.

Also cosigners will need to communicate other information as well, namely exchange
their public keys to each other before uploading to the server. Because
operator can change cosigners xpub before adding to the wallet, you need some way
to make sure cosigner xpubs that were added to the wallet belong to cosigners.
If you have other cosigners public keys you can verify wallet has correct xpubs.
This is similar problem to what GPG is trying to solve using Web of Trust (which
does not scale well, especially for short term public keys that you switch for each
cosigner set.)

To summurize, in order to remove operator trust from current structure, users
will have to exchange and verify each others public keys before uploading to the
server and always verify that keys on the server have not changed.

I would say, it's easier to build different architecture with trustless
architecture from the beginning.

### lightweight joinKey verification

I think this is something that addresses second point more. To make joining easier,
less information to exchange, we could have:
  - wallet name
  - creators signature from some derivation (branch=x?)
    - sign(sha256(wallet name)) - maybe with random number..

This can prevent accidentally joining to wrong wallet and having to know wallet name before
joining. (You still need to track wallet name afterwords to use the features.)
Signature will also make sure you don't accidentally join wrong wallet and you have the
joinKey from the creator.

This wont save you from operator attacks or insecure joinKey sharing.
Make it more convenient in some cases. Only downside being, you need to sign
something in order to create, which in some cases may not be desired.

Note: We could also include apiKey but that will be different enough from bwallet,
that we might as well change couple more things about apiKey (Switch to public
API like apiKeys, where it will be different for each cosigner).

**Comment by BluSyn** [comment]
1) Agreed this doesn't help much in the scenario of full admin control, but does help with other users who may have API access. Additionally I am not convinced SSL is enough protection against MITM. It seems minimal overhead to make the join key cryptographic verification rather than just a hash comparison. Removing full operator trust in this system is not really possible, but we certainly can make it better. 

2) We can exclude `apiKey`, agree that isn't necessary in this context. We can discuss more complicated auth schemes separately.

Wallet Name is the key information that would be helpful to add.

This is more about creating a standard serialization format for the join process, and while this could just be handled client side, I would prefer to do this on the server-side for consistency.

> Only downside being, you need to sign
something in order to create, which in some cases may not be desired.

I think this is preferable. See BWS, where a signature is required from each cosigner as they join. I think we can make this even better by confirming the cosigner is joining with a private key they actually posses, and not just a random xpub.

See this for reference on how we can potentially add security to join process and tx proposals.

BWS:
https://github.com/bitpay/bitcore/tree/master/packages/bitcore-wallet-service#security-considerations

**Comment by tynes** [comment]
@nodar-chkuaselidze what are your thoughts after looking at steven's most recent post?
